knpu_oauth2_client:
    clients:
        facebook:
            type: facebook
            client_id: '%env(FACEBOOK_CLIENT_ID)%'
            client_secret: '%env(FACEBOOK_CLIENT_SECRET)%'
            redirect_route: connect_facebook_check
            redirect_params: {}
            graph_api_version: v18.0
            use_state: true
